/**
 * Québec Trade Directory — seed listings.
 * Replace or extend via import script / API as needed.
 */

const TRADE_TYPES = [
  "Acoustic ceiling (T-bar)",
  "Appliance repair technician",
  "Arborist & tree care",
  "Asbestos & mould abatement",
  "Asphalt paving & sealcoating",
  "Boilermaker",
  "Building automation & controls",
  "Cabinet maker / millwork",
  "Carpenter / framer",
  "Chimney sweep (WETT-certified)",
  "Concrete / foundation",
  "Concrete pump operator",
  "Crane & hoisting services",
  "Demolition",
  "Drywaller / taper",
  "Duct cleaning",
  "Electrician",
  "Elevator technician",
  "Energy advisor (EnerGuide)",
  "Epoxy & polished concrete",
  "Excavation / grading",
  "Fence & deck",
  "Fire stopping & fireproofing",
  "Flooring installer",
  "Formwork carpenter",
  "Garage door",
  "Gas fitter",
  "General contractor",
  "Generator & backup power",
  "Glazier / windows & doors",
  "Handyman services",
  "Home inspector",
  "HVAC / mechanical",
  "Hydrovac operator",
  "Industrial coatings & blasting",
  "Insulation",
  "Interlock & hardscape",
  "Ironworker & steel erection",
  "Land surveyor / layout",
  "Landscaper",
  "Locksmith",
  "Low-voltage / security",
  "Mason / bricklayer",
  "Millwright",
  "Painter",
  "Parking lot line painting",
  "Pile driving & deep foundations",
  "Pipefitter & steamfitter",
  "Plasterer & stucco",
  "Plumber",
  "Pool & spa technician",
  "Refrigeration mechanic",
  "Renovation contractor",
  "Restoration (fire / flood)",
  "Roofer",
  "Scaffolding & swing stage",
  "Septic & well",
  "Sheet metal worker",
  "Shoring & underpinning",
  "Shower glass & railings",
  "Siding / eavestrough",
  "Sign & graphics installer",
  "Snow & ice management",
  "Solar installer",
  "Sprinkler / fire protection",
  "Tile & stone installer",
  "Traffic control (TCP)",
  "Utility locating (private)",
  "Waterproofer",
  "Welder / metal fab",
  "Window cleaning",
];

const REGIONS = [
  "Greater Montréal",
  "Laval & Laurentides",
  "Montérégie",
  "Québec City & Chaudière-Appalaches",
  "Centre-du-Québec",
  "Estrie",
  "Mauricie",
  "Outaouais",
  "Saguenay–Lac-Saint-Jean",
  "Bas-Saint-Laurent & Gaspésie",
  "Côte-Nord, Nord-du-Québec & Abitibi",
];

/** Stock photos (Unsplash) matched to trade type — swap for your own assets anytime. */
const TRADE_IMAGES = {
  "Acoustic ceiling (T-bar)":
    "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=640&h=360&fit=crop&q=80",
  "Appliance repair technician":
    "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=640&h=360&fit=crop&q=80",
  "Arborist & tree care":
    "https://images.unsplash.com/photo-1448375261783-1d5b7e710b03?w=640&h=360&fit=crop&q=80",
  "Asbestos & mould abatement":
    "https://images.unsplash.com/photo-1584820927498-cf99d7c2f785?w=640&h=360&fit=crop&q=80",
  "Asphalt paving & sealcoating":
    "https://images.unsplash.com/photo-1625246333195-78d9c42ad36b?w=640&h=360&fit=crop&q=80",
  Boilermaker:
    "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=640&h=360&fit=crop&q=80",
  "Building automation & controls":
    "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=640&h=360&fit=crop&q=80",
  "Cabinet maker / millwork":
    "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=640&h=360&fit=crop&q=80",
  "Carpenter / framer":
    "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=640&h=360&fit=crop&q=80",
  "Chimney sweep (WETT-certified)":
    "https://images.unsplash.com/photo-1513467535987-fd81ac7cdd6c?w=640&h=360&fit=crop&q=80",
  "Concrete / foundation":
    "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=640&h=360&fit=crop&q=80",
  "Concrete pump operator":
    "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=640&h=360&fit=crop&q=80",
  "Crane & hoisting services":
    "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=640&h=360&fit=crop&q=80",
  Demolition:
    "https://images.unsplash.com/photo-1531834685032-c34bf0d84c7c?w=640&h=360&fit=crop&q=80",
  "Drywaller / taper":
    "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=640&h=360&fit=crop&q=80",
  "Duct cleaning":
    "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=640&h=360&fit=crop&q=80",
  Electrician:
    "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=640&h=360&fit=crop&q=80",
  "Elevator technician":
    "https://images.unsplash.com/photo-1560185007-c5ca9d2c014d?w=640&h=360&fit=crop&q=80",
  "Energy advisor (EnerGuide)":
    "https://images.unsplash.com/photo-1497435334941-0c349ee58c99?w=640&h=360&fit=crop&q=80",
  "Epoxy & polished concrete":
    "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=640&h=360&fit=crop&q=80",
  "Excavation / grading":
    "https://images.unsplash.com/photo-1581092918056-0c4c3acd378c?w=640&h=360&fit=crop&q=80",
  "Fence & deck":
    "https://images.unsplash.com/photo-1599619351208-207e3c0b793c?w=640&h=360&fit=crop&q=80",
  "Fire stopping & fireproofing":
    "https://images.unsplash.com/photo-1581822261290-913bec1cf798?w=640&h=360&fit=crop&q=80",
  "Flooring installer":
    "https://images.unsplash.com/photo-1615529328331-f8917597711f?w=640&h=360&fit=crop&q=80",
  "Formwork carpenter":
    "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=640&h=360&fit=crop&q=80",
  "Garage door":
    "https://images.unsplash.com/photo-1558036117-15d90a7326b9?w=640&h=360&fit=crop&q=80",
  "Gas fitter":
    "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=640&h=360&fit=crop&q=80",
  "General contractor":
    "https://images.unsplash.com/photo-1503389152954-9f71852786d9?w=640&h=360&fit=crop&q=80",
  "Generator & backup power":
    "https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=640&h=360&fit=crop&q=80",
  "Glazier / windows & doors":
    "https://images.unsplash.com/photo-1497366216548-37526070297c?w=640&h=360&fit=crop&q=80",
  "Handyman services":
    "https://images.unsplash.com/photo-1504148455328-c376907d081c?w=640&h=360&fit=crop&q=80",
  "Home inspector":
    "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=640&h=360&fit=crop&q=80",
  "HVAC / mechanical":
    "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=640&h=360&fit=crop&q=80",
  "Hydrovac operator":
    "https://images.unsplash.com/photo-1581092918056-0c4c3acd378c?w=640&h=360&fit=crop&q=80",
  "Industrial coatings & blasting":
    "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=640&h=360&fit=crop&q=80",
  Insulation:
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=640&h=360&fit=crop&q=80",
  "Interlock & hardscape":
    "https://images.unsplash.com/photo-1416879595882-3373a0480b5a?w=640&h=360&fit=crop&q=80",
  "Ironworker & steel erection":
    "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=640&h=360&fit=crop&q=80",
  "Land surveyor / layout":
    "https://images.unsplash.com/photo-1503389152954-9f71852786d9?w=640&h=360&fit=crop&q=80",
  Landscaper:
    "https://images.unsplash.com/photo-1416879595882-3373a0480b5a?w=640&h=360&fit=crop&q=80",
  Locksmith:
    "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=640&h=360&fit=crop&q=80",
  "Low-voltage / security":
    "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=640&h=360&fit=crop&q=80",
  "Mason / bricklayer":
    "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=640&h=360&fit=crop&q=80",
  Millwright:
    "https://images.unsplash.com/photo-1565043666747-69f008b433aa?w=640&h=360&fit=crop&q=80",
  Painter:
    "https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=640&h=360&fit=crop&q=80",
  "Parking lot line painting":
    "https://images.unsplash.com/photo-1565008578689-67a3b5b90c0e?w=640&h=360&fit=crop&q=80",
  "Pile driving & deep foundations":
    "https://images.unsplash.com/photo-1581092918056-0c4c3acd378c?w=640&h=360&fit=crop&q=80",
  "Pipefitter & steamfitter":
    "https://images.unsplash.com/photo-1585705528105-a8eade5f52b1?w=640&h=360&fit=crop&q=80",
  "Plasterer & stucco":
    "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=640&h=360&fit=crop&q=80",
  Plumber:
    "https://images.unsplash.com/photo-1585705528105-a8eade5f52b1?w=640&h=360&fit=crop&q=80",
  "Pool & spa technician":
    "https://images.unsplash.com/photo-1576013551627-e0bcad6ad6e6?w=640&h=360&fit=crop&q=80",
  "Refrigeration mechanic":
    "https://images.unsplash.com/photo-1581579188871-b7fb6e0a9065?w=640&h=360&fit=crop&q=80",
  "Renovation contractor":
    "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=640&h=360&fit=crop&q=80",
  "Restoration (fire / flood)":
    "https://images.unsplash.com/photo-1565538810643-b5bdb714032a?w=640&h=360&fit=crop&q=80",
  Roofer:
    "https://images.unsplash.com/photo-1632759145351-082d9e2989c6?w=640&h=360&fit=crop&q=80",
  "Scaffolding & swing stage":
    "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=640&h=360&fit=crop&q=80",
  "Septic & well":
    "https://images.unsplash.com/photo-1545558014-8692077e9b5c?w=640&h=360&fit=crop&q=80",
  "Sheet metal worker":
    "https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=640&h=360&fit=crop&q=80",
  "Shoring & underpinning":
    "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=640&h=360&fit=crop&q=80",
  "Shower glass & railings":
    "https://images.unsplash.com/photo-1620626011763-996317434e20?w=640&h=360&fit=crop&q=80",
  "Siding / eavestrough":
    "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=640&h=360&fit=crop&q=80",
  "Sign & graphics installer":
    "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=640&h=360&fit=crop&q=80",
  "Snow & ice management":
    "https://images.unsplash.com/photo-1551524164-687a55dd1127?w=640&h=360&fit=crop&q=80",
  "Solar installer":
    "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=640&h=360&fit=crop&q=80",
  "Sprinkler / fire protection":
    "https://images.unsplash.com/photo-1581822261290-913bec1cf798?w=640&h=360&fit=crop&q=80",
  "Tile & stone installer":
    "https://images.unsplash.com/photo-1600585154526-990dcecc4e9f?w=640&h=360&fit=crop&q=80",
  "Traffic control (TCP)":
    "https://images.unsplash.com/photo-1449965408869-eaa3f721e1d5?w=640&h=360&fit=crop&q=80",
  "Utility locating (private)":
    "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=640&h=360&fit=crop&q=80",
  Waterproofer:
    "https://images.unsplash.com/photo-1523413363574-c30aa1c2e476?w=640&h=360&fit=crop&q=80",
  "Welder / metal fab":
    "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=640&h=360&fit=crop&q=80",
  "Window cleaning":
    "https://images.unsplash.com/photo-1563453396-422f98f88fd7?w=640&h=360&fit=crop&q=80",
};

const DEFAULT_LISTING_IMAGE =
  "https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=640&h=360&fit=crop&q=80";

const LISTINGS = [
  {
    id: "1",
    name: "Lakeview Plumbing Co.",
    trade: "Plumber",
    city: "Montreal",
    region: "Greater Montréal",
    phone: "+1-416-555-0101",
    description: "Residential & commercial service, drain cleaning, rough-ins.",
    website: "https://example.com/lakeview-plumbing",
    licensed: true,
  },
  {
    id: "2",
    name: "Capital City Electric Ltd.",
    trade: "Electrician",
    city: "Québec",
    region: "Québec City & Chaudière-Appalaches",
    phone: "+1-613-555-0202",
    description: "Panel upgrades, EV chargers, lighting design.",
    licensed: true,
  },
  {
    id: "3",
    name: "Niagara Peak Roofing",
    trade: "Roofer",
    city: "Laval",
    region: "Laval & Laurentides",
    phone: "+1-905-555-0303",
    description: "Asphalt, metal, flat roofs; ice dam prevention.",
    licensed: true,
  },
  {
    id: "4",
    name: "Comfort Zone HVAC",
    trade: "HVAC / mechanical",
    city: "Gatineau",
    region: "Outaouais",
    phone: "+1-905-555-0404",
    description: "Furnace, AC, heat pumps; maintenance plans.",
    licensed: true,
  },
  {
    id: "5",
    name: "True North Carpentry",
    trade: "Carpenter / framer",
    city: "Longueuil",
    region: "Greater Montréal",
    phone: "+1-807-555-0505",
    description: "Custom framing, additions, garages.",
    licensed: false,
  },
  {
    id: "6",
    name: "Smooth Wall Taping",
    trade: "Drywaller / taper",
    city: "Sherbrooke",
    region: "Estrie",
    phone: "+1-519-555-0606",
    description: "Level 5 finish, repairs, popcorn removal.",
  },
  {
    id: "7",
    name: "Brush & Barrel Painting",
    trade: "Painter",
    city: "Trois-Rivières",
    region: "Mauricie",
    phone: "+1-519-555-0707",
    description: "Interior/exterior, spray, cabinet refinishing.",
    licensed: true,
  },
  {
    id: "8",
    name: "Heritage Brickworks",
    trade: "Mason / bricklayer",
    city: "Saguenay",
    region: "Saguenay–Lac-Saint-Jean",
    phone: "+1-613-555-0808",
    description: "Repointing, chimneys, stone veneer.",
    licensed: true,
  },
  {
    id: "9",
    name: "Solid Base Concrete",
    trade: "Concrete / foundation",
    city: "Rimouski",
    region: "Bas-Saint-Laurent & Gaspésie",
    phone: "+1-519-555-0909",
    description: "Footings, basement floors, decorative flatwork.",
    licensed: true,
  },
  {
    id: "10",
    name: "Maple Grove Floors",
    trade: "Flooring installer",
    city: "Saint-Jean-sur-Richelieu",
    region: "Montérégie",
    phone: "+1-905-555-1010",
    description: "Hardwood, LVP, tile; subfloor prep.",
  },
  {
    id: "11",
    name: "Greenbelt Landscapes",
    trade: "Landscaper",
    city: "Drummondville",
    region: "Centre-du-Québec",
    phone: "+1-905-555-1111",
    description: "Design-build, interlock, drainage, planting.",
    licensed: true,
  },
  {
    id: "12",
    name: "North Ridge Excavating",
    trade: "Excavation / grading",
    city: "Granby",
    region: "Estrie",
    phone: "+1-705-555-1212",
    description: "Site prep, trenching, winter access.",
  },
  {
    id: "13",
    name: "CozyCell Insulation",
    trade: "Insulation",
    city: "Victoriaville",
    region: "Centre-du-Québec",
    phone: "+1-519-555-1313",
    description: "Blown-in, spray foam, attic top-ups.",
    licensed: true,
  },
  {
    id: "14",
    name: "ClearView Glass & Door",
    trade: "Glazier / windows & doors",
    city: "Sept-Îles",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-905-555-1414",
    description: "Retrofit windows, storefront, tempered glass.",
  },
  {
    id: "15",
    name: "EaveRight Exteriors",
    trade: "Siding / eavestrough",
    city: "Val-d'Or",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-905-555-1515",
    description: "Vinyl & fibre cement siding, seamless gutters.",
    licensed: true,
  },
  {
    id: "16",
    name: "Blueprint General Contracting",
    trade: "General contractor",
    city: "Rouyn-Noranda",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-416-555-1616",
    description: "Mid-rise fit-outs, industrial TI, project management.",
    licensed: true,
  },
  {
    id: "17",
    name: "Renewal Home Reno",
    trade: "Renovation contractor",
    city: "Gaspé",
    region: "Bas-Saint-Laurent & Gaspésie",
    phone: "+1-705-555-1717",
    description: "Kitchens, baths, basements; design assist.",
    licensed: true,
  },
  {
    id: "18",
    name: "IronBridge Welding",
    trade: "Welder / metal fab",
    city: "Blainville",
    region: "Laval & Laurentides",
    phone: "+1-705-555-1818",
    description: "Structural steel, custom railings, mobile repairs.",
  },
  {
    id: "19",
    name: "SafeFlame Gas Services",
    trade: "Gas fitter",
    city: "Terrebonne",
    region: "Laval & Laurentides",
    phone: "+1-519-555-1919",
    description: "Gas lines, appliances, inspections.",
    licensed: true,
  },
  {
    id: "20",
    name: "DryShield Basement Systems",
    trade: "Waterproofer",
    city: "Repentigny",
    region: "Greater Montréal",
    phone: "+1-613-555-2020",
    description: "Interior perimeter drains, sump pumps, crack injection.",
    licensed: true,
  },
  {
    id: "21",
    name: "Rapid Strip Demolition",
    trade: "Demolition",
    city: "Saint-Hyacinthe",
    region: "Montérégie",
    phone: "+1-519-555-2121",
    description: "Selective demo, abatement coordination.",
  },
  {
    id: "22",
    name: "FreshStart Restoration",
    trade: "Restoration (fire / flood)",
    city: "Salaberry-de-Valleyfield",
    region: "Montérégie",
    phone: "+1-905-555-2222",
    description: "Emergency response, mould remediation, rebuild.",
    licensed: true,
  },
  {
    id: "23",
    name: "VerticalLift Service",
    trade: "Elevator technician",
    city: "Joliette",
    region: "Laval & Laurentides",
    phone: "+1-416-555-2323",
    description: "Maintenance contracts, modernizations.",
    licensed: true,
  },
  {
    id: "24",
    name: "KeyMaster Locksmith",
    trade: "Locksmith",
    city: "Shawinigan",
    region: "Mauricie",
    phone: "+1-705-555-2424",
    description: "Residential rekey, access control, safes.",
  },
  {
    id: "25",
    name: "Cedarline Decks & Fences",
    trade: "Fence & deck",
    city: "Brossard",
    region: "Greater Montréal",
    phone: "+1-705-555-2525",
    description: "Pressure-treated, composite, privacy screens.",
  },
  {
    id: "26",
    name: "Northern Sun Solar",
    trade: "Solar installer",
    city: "Lévis",
    region: "Québec City & Chaudière-Appalaches",
    phone: "+1-705-555-2626",
    description: "Residential arrays, battery backup planning.",
    licensed: true,
  },
  {
    id: "27",
    name: "SprinklerPro Fire",
    trade: "Sprinkler / fire protection",
    city: "Montreal",
    region: "Greater Montréal",
    phone: "+1-905-555-2727",
    description: "NFPA inspections, tenant improvements.",
    licensed: true,
  },
  {
    id: "28",
    name: "WireWise Low Voltage",
    trade: "Low-voltage / security",
    city: "Québec",
    region: "Québec City & Chaudière-Appalaches",
    phone: "+1-519-555-2828",
    description: "Structured cabling, cameras, access control.",
  },
  {
    id: "29",
    name: "AquaWell Septic",
    trade: "Septic & well",
    city: "Laval",
    region: "Laval & Laurentides",
    phone: "+1-613-555-2929",
    description: "Septic installs, pump-outs, well diagnostics.",
    licensed: true,
  },
  {
    id: "30",
    name: "RiseUp Garage Doors",
    trade: "Garage door",
    city: "Gatineau",
    region: "Outaouais",
    phone: "+1-905-555-3030",
    description: "Install, openers, spring replacement.",
  },
  {
    id: "31",
    name: "Bay Street Plumbing",
    trade: "Plumber",
    city: "Longueuil",
    region: "Greater Montréal",
    phone: "+1-416-555-3131",
    description: "High-rise stacks, suite rough-ins.",
    licensed: true,
    image:
      "https://images.unsplash.com/photo-1607472586893-9c886b243e0c?w=640&h=360&fit=crop&q=80",
  },
  {
    id: "32",
    name: "Rideau Electric",
    trade: "Electrician",
    city: "Sherbrooke",
    region: "Estrie",
    phone: "+1-613-555-3232",
    description: "Knob & tube replacement, service upgrades.",
    licensed: true,
    image:
      "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=640&h=360&fit=crop&q=80",
  },
  {
    id: "33",
    name: "Steel City Roofing",
    trade: "Roofer",
    city: "Trois-Rivières",
    region: "Mauricie",
    phone: "+1-905-555-3333",
    description: "Commercial membrane, metal retrofit.",
    licensed: true,
    image:
      "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=640&h=360&fit=crop&q=80",
  },
  {
    id: "34",
    name: "Gridline Acoustic Ltd.",
    trade: "Acoustic ceiling (T-bar)",
    city: "Saguenay",
    region: "Saguenay–Lac-Saint-Jean",
    phone: "+1-416-555-3401",
    description: "T-bar, baffles, specialty ceilings for offices and retail.",
    licensed: true,
  },
  {
    id: "35",
    name: "Northern Appliance Doctor",
    trade: "Appliance repair technician",
    city: "Rimouski",
    region: "Bas-Saint-Laurent & Gaspésie",
    phone: "+1-705-555-3502",
    description: "Factory-trained on most brands; warranty-capable service calls.",
  },
  {
    id: "36",
    name: "Canopy Tree Experts",
    trade: "Arborist & tree care",
    city: "Saint-Jean-sur-Richelieu",
    region: "Montérégie",
    phone: "+1-519-555-3603",
    description: "ISA-certified pruning, removals, plant health, cabling.",
    licensed: true,
  },
  {
    id: "37",
    name: "SafeSpace Abatement Québec",
    trade: "Asbestos & mould abatement",
    city: "Drummondville",
    region: "Centre-du-Québec",
    phone: "+1-905-555-3704",
    description: "Type 3 containment, air monitoring, clearance certificates.",
    licensed: true,
  },
  {
    id: "38",
    name: "Blacktop Bros Paving",
    trade: "Asphalt paving & sealcoating",
    city: "Granby",
    region: "Estrie",
    phone: "+1-519-555-3805",
    description: "Driveways, parking lots, municipal patching, line painting partners.",
  },
  {
    id: "39",
    name: "Great Lakes Boilermakers Guild",
    trade: "Boilermaker",
    city: "Victoriaville",
    region: "Centre-du-Québec",
    phone: "+1-519-555-3906",
    description: "Pressure vessels, boil-outs, shutdown support for industrial sites.",
    licensed: true,
  },
  {
    id: "40",
    name: "ClimaLogic BMS",
    trade: "Building automation & controls",
    city: "Sept-Îles",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-613-555-4007",
    description: "DDC programming, BACnet, analytics, retro-commissioning.",
    licensed: true,
  },
  {
    id: "41",
    name: "Heartwood Custom Cabinets",
    trade: "Cabinet maker / millwork",
    city: "Val-d'Or",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-705-555-4108",
    description: "Kitchens, built-ins, commercial reception millwork; shop drawings.",
  },
  {
    id: "42",
    name: "FlueWise Chimney Services",
    trade: "Chimney sweep (WETT-certified)",
    city: "Rouyn-Noranda",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-519-555-4209",
    description: "WETT inspections, liner installs, masonry chimney repairs.",
    licensed: true,
  },
  {
    id: "43",
    name: "FlowLine Concrete Pumping",
    trade: "Concrete pump operator",
    city: "Gaspé",
    region: "Bas-Saint-Laurent & Gaspésie",
    phone: "+1-905-555-4310",
    description: "Line pump and boom placements; high-rise and ICI projects.",
  },
  {
    id: "44",
    name: "Skyhook Crane Rental",
    trade: "Crane & hoisting services",
    city: "Blainville",
    region: "Laval & Laurentides",
    phone: "+1-519-555-4411",
    description: "CPA-certified operators, lift plans, mobile crane 40–240 t.",
    licensed: true,
  },
  {
    id: "45",
    name: "VentRight Duct Cleaning",
    trade: "Duct cleaning",
    city: "Terrebonne",
    region: "Laval & Laurentides",
    phone: "+1-905-555-4512",
    description: "Residential and light commercial; dryer vent and HVAC sanitation.",
  },
  {
    id: "46",
    name: "EnerGuide North",
    trade: "Energy advisor (EnerGuide)",
    city: "Repentigny",
    region: "Greater Montréal",
    phone: "+1-705-555-4613",
    description: "Registered energy advisors; pre/post retrofit EnerGuide ratings.",
    licensed: true,
  },
  {
    id: "47",
    name: "MirrorKote Epoxy Floors",
    trade: "Epoxy & polished concrete",
    city: "Saint-Hyacinthe",
    region: "Montérégie",
    phone: "+1-519-555-4714",
    description: "Industrial epoxy, urethane, polished concrete for warehouses & shops.",
  },
  {
    id: "48",
    name: "StopFire Passive Protection",
    trade: "Fire stopping & fireproofing",
    city: "Salaberry-de-Valleyfield",
    region: "Montérégie",
    phone: "+1-905-555-4815",
    description: "UL-listed firestop systems, penetration audits, ULTRA listings support.",
    licensed: true,
  },
  {
    id: "49",
    name: "TrueForm Shoring",
    trade: "Formwork carpenter",
    city: "Joliette",
    region: "Laval & Laurentides",
    phone: "+1-416-555-4916",
    description: "Vertical formwork, gang forms, slab on grade for high-rise.",
  },
  {
    id: "50",
    name: "Blackout Generator Group",
    trade: "Generator & backup power",
    city: "Shawinigan",
    region: "Mauricie",
    phone: "+1-905-555-5017",
    description: "Whole-home and commercial standby, ATS, maintenance contracts.",
    licensed: true,
  },
  {
    id: "51",
    name: "OddJob Québec",
    trade: "Handyman services",
    city: "Brossard",
    region: "Greater Montréal",
    phone: "+1-613-555-5118",
    description: "Small repairs, assembly, drywall patches, trim — booked by half-day.",
  },
  {
    id: "52",
    name: "BrickByBrick Home Inspections",
    trade: "Home inspector",
    city: "Lévis",
    region: "Québec City & Chaudière-Appalaches",
    phone: "+1-613-555-5219",
    description: "Carson Dunlop–trained; thermal imaging & detailed defect reporting.",
    licensed: true,
  },
  {
    id: "53",
    name: "HydroVac Québec",
    trade: "Hydrovac operator",
    city: "Montreal",
    region: "Greater Montréal",
    phone: "+1-807-555-5320",
    description: "Daylighting, slot trenching, pit cleaning for utilities.",
  },
  {
    id: "54",
    name: "BlastPro Coatings",
    trade: "Industrial coatings & blasting",
    city: "Québec",
    region: "Québec City & Chaudière-Appalaches",
    phone: "+1-905-555-5421",
    description: "Contained blasting, intumescent paint, tank linings.",
    licensed: true,
  },
  {
    id: "55",
    name: "StonePath Interlock",
    trade: "Interlock & hardscape",
    city: "Laval",
    region: "Laval & Laurentides",
    phone: "+1-905-555-5522",
    description: "Permeable pavers, retaining walls, natural stone patios.",
  },
  {
    id: "56",
    name: "RedIron Steel Erectors",
    trade: "Ironworker & steel erection",
    city: "Gatineau",
    region: "Outaouais",
    phone: "+1-519-555-5623",
    description: "Structural steel, pre-engineered buildings, rebar placing crews.",
    licensed: true,
  },
  {
    id: "57",
    name: "PinPoint Surveying",
    trade: "Land surveyor / layout",
    city: "Longueuil",
    region: "Greater Montréal",
    phone: "+1-613-555-5724",
    description: "OLQPPS surveys, construction layout, as-builts for civil work.",
    licensed: true,
  },
  {
    id: "58",
    name: "Rotary Mill Services",
    trade: "Millwright",
    city: "Sherbrooke",
    region: "Estrie",
    phone: "+1-519-555-5825",
    description: "Precision alignments, conveyor installs, production line moves.",
    licensed: true,
  },
  {
    id: "59",
    name: "Brightstripe Lot Markings",
    trade: "Parking lot line painting",
    city: "Trois-Rivières",
    region: "Mauricie",
    phone: "+1-905-555-5926",
    description: "Thermoplastic, MMA, stencils, accessible stalls to OBC.",
  },
  {
    id: "60",
    name: "DeepSet Piling",
    trade: "Pile driving & deep foundations",
    city: "Saguenay",
    region: "Saguenay–Lac-Saint-Jean",
    phone: "+1-416-555-6027",
    description: "Driven H-piles, CFA, shoring tie-ins with geotech coordination.",
  },
  {
    id: "61",
    name: "SteamWorks Pipefitting",
    trade: "Pipefitter & steamfitter",
    city: "Rimouski",
    region: "Bas-Saint-Laurent & Gaspésie",
    phone: "+1-905-555-6128",
    description: "Process piping, high-pressure steam, orbital welding support.",
    licensed: true,
  },
  {
    id: "62",
    name: "Stucco Nova Finishes",
    trade: "Plasterer & stucco",
    city: "Saint-Jean-sur-Richelieu",
    region: "Montérégie",
    phone: "+1-519-555-6229",
    description: "EIFS repair, traditional stucco, parging, scratch & brown coats.",
  },
  {
    id: "63",
    name: "Crystal Cove Pools",
    trade: "Pool & spa technician",
    city: "Drummondville",
    region: "Centre-du-Québec",
    phone: "+1-705-555-6330",
    description: "Openings, heaters, vinyl liner, leak detection, salt systems.",
    licensed: true,
  },
  {
    id: "64",
    name: "ArcticCold Refrigeration",
    trade: "Refrigeration mechanic",
    city: "Granby",
    region: "Estrie",
    phone: "+1-613-555-6431",
    description: "Walk-in coolers, ice rinks, rack systems, 24/7 emergency.",
    licensed: true,
  },
  {
    id: "65",
    name: "ReachSafe Scaffolding",
    trade: "Scaffolding & swing stage",
    city: "Victoriaville",
    region: "Centre-du-Québec",
    phone: "+1-416-555-6532",
    description: "Frame & system scaffold, swing stage, swing stage techs on staff.",
    licensed: true,
  },
  {
    id: "66",
    name: "AirFlow Sheet Metal",
    trade: "Sheet metal worker",
    city: "Sept-Îles",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-519-555-6633",
    description: "Custom duct, kitchen exhaust, SMACNA fabrication & install.",
    licensed: true,
  },
  {
    id: "67",
    name: "Bedrock Shoring Inc.",
    trade: "Shoring & underpinning",
    city: "Val-d'Or",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-416-555-6734",
    description: "Underpinning, needle beams, helical piers for tight urban lots.",
    licensed: true,
  },
  {
    id: "68",
    name: "Frameless Direct",
    trade: "Shower glass & railings",
    city: "Rouyn-Noranda",
    region: "Côte-Nord, Nord-du-Québec & Abitibi",
    phone: "+1-905-555-6835",
    description: "10 mm tempered, clips & channels, glass railings to code.",
  },
  {
    id: "69",
    name: "Skyline Sign & Vinyl",
    trade: "Sign & graphics installer",
    city: "Gaspé",
    region: "Bas-Saint-Laurent & Gaspésie",
    phone: "+1-519-555-6936",
    description: "Channel letters, fleet wraps, permit packages with engineers.",
  },
  {
    id: "70",
    name: "PolarLot Snow Command",
    trade: "Snow & ice management",
    city: "Blainville",
    region: "Laval & Laurentides",
    phone: "+1-905-555-7037",
    description: "Salt tracking, sidewalk crews, loader boxes for retail portfolios.",
    licensed: true,
  },
  {
    id: "71",
    name: "Tessera Tile Studio",
    trade: "Tile & stone installer",
    city: "Terrebonne",
    region: "Laval & Laurentides",
    phone: "+1-416-555-7138",
    description: "Large-format, waterproofing, steam showers, natural stone.",
  },
  {
    id: "72",
    name: "FlagRight Traffic",
    trade: "Traffic control (TCP)",
    city: "Repentigny",
    region: "Greater Montréal",
    phone: "+1-905-555-7239",
    description: "Book 7 setups, lane closures, special event TCP plans.",
    licensed: true,
  },
  {
    id: "73",
    name: "LocateFirst Private",
    trade: "Utility locating (private)",
    city: "Saint-Hyacinthe",
    region: "Montérégie",
    phone: "+1-519-555-7340",
    description: "GPR, EM locating, mark-outs before dig for contractors.",
  },
  {
    id: "74",
    name: "PaneKing Window Cleaning",
    trade: "Window cleaning",
    city: "Salaberry-de-Valleyfield",
    region: "Montérégie",
    phone: "+1-416-555-7441",
    description: "High-rise rope access & boom; rinse & pure-water residential.",
    licensed: true,
  },
];

/** Listing ids with no public website (optional field omitted from cards). */
const LISTING_IDS_WITHOUT_WEBSITE = new Set([
  "5",
  "12",
  "21",
  "24",
  "35",
  "45",
  "51",
  "53",
  "69",
  "73",
]);

for (const L of LISTINGS) {
  if (LISTING_IDS_WITHOUT_WEBSITE.has(L.id)) continue;
  if (!L.website) {
    L.website = `https://example.com/trades/${L.id}`;
  }
}

/** Optional fields merged for demo: verified, hours, reviews { rating, count } */
const LISTING_ENRICHMENT = {
  "1": { verified: true, hours: "Mon–Fri 7am–6pm · Sat 8–2 · emergency line", reviews: { rating: 4.9, count: 128 } },
  "2": { verified: true, hours: "Mon–Fri 8–5 · 24/7 emergency", reviews: { rating: 4.8, count: 86 } },
  "3": { verified: true, hours: "Mon–Sat 7–7", reviews: { rating: 4.7, count: 54 } },
  "4": { verified: true, hours: "Mon–Sat 8–8", reviews: { rating: 4.6, count: 203 } },
  "16": { verified: true, hours: "Office Mon–Fri 8–5", reviews: { rating: 4.9, count: 42 } },
  "22": { verified: true, hours: "Emergency 24/7", reviews: { rating: 4.5, count: 91 } },
  "31": { verified: true, reviews: { rating: 4.4, count: 37 } },
  "40": { verified: true, hours: "Mon–Fri 7–4", reviews: { rating: 5.0, count: 19 } },
  "52": { verified: true, hours: "Bookings Mon–Sun", reviews: { rating: 4.9, count: 312 } },
  "71": { verified: true, hours: "Showroom Tue–Sat 10–4", reviews: { rating: 4.8, count: 67 } },
  "11": { reviews: { rating: 4.3, count: 22 } },
  "27": { reviews: { rating: 4.7, count: 15 } },
};

for (const L of LISTINGS) {
  const extra = LISTING_ENRICHMENT[L.id];
  if (extra) Object.assign(L, extra);
}

window.TRADE_DIRECTORY = {
  TRADE_TYPES,
  REGIONS,
  LISTINGS,
  TRADE_IMAGES,
  DEFAULT_LISTING_IMAGE,
};
